ln -sf /home/$1/dotfiles/zsh/.zshrc /home/$1/.zshrc
ln -sf /home/$1/dotfiles/zsh/wetslap7.zsh-theme /home/$1/.oh-my-zsh/themes/wetslap7.zsh-theme
ln -sf /home/$1/dotfiles/zsh/.zsh_history /home/$1/.zsh_history
ln -sf /home/$1/dotfiles/vim/.vimrc /home/$1/.vimrc
ln -sf /home/$1/dotfiles/vim/.vim/colors /home/$1/.vim/colors
ln -sf /home/$1/dotfiles/kde/konsole/konsole /home/$1/.kde4/share/apps/konsole
ln -sf /home/$1/dotfiles/kde/konsole/konsolerc /home/$1/.kde4/share/config/konsolerc
ln -sf /home/$1/dotfiles/kde/kwallet/kwalletrc /home/$1/.kde4/share/config/kwalletrc
ln -sf /home/$1/dotfiles/config/touchpadrc /home/$1/.config/touchpadrc
ln -sf /home/$1/dotfiles/config/kwalletrc /home/$1/.config/kwalletrc
ln -sf /home/$1/dotfiles/git/.gitconfig /home/$1/.gitconfig
ln -sf /home/$1/dotfiles/etc/sddm.conf /etc/sddm.conf
ln -sf /home/$1/dotfiles/etc/hostname /etc/hostname
ln -sf /home/$1/dotfiles/etc/locale.conf /etc/locale.conf
